// Generated by scripts/generate-image-requires.ts — do not edit by hand.
// Run `npm run generate:images` to regenerate this file.

export const images128Path = {
  profile1: require("./128/1.png"),
  profile2: require("./128/2.png"),
  profile3: require("./128/3.png"),
  profile4: require("./128/4.png"),
  profile5: require("./128/5.png"),
  profile6: require("./128/6.png"),
  profile7: require("./128/7.png"),
  profile8: require("./128/8.png"),
  profile9: require("./128/9.png"),
  profile10: require("./128/10.png"),
} as const;

export const image128Array = [
  images128Path.profile1,
  images128Path.profile2,
  images128Path.profile3,
  images128Path.profile4,
  images128Path.profile5,
  images128Path.profile6,
  images128Path.profile7,
  images128Path.profile8,
  images128Path.profile9,
  images128Path.profile10,
] as const;

export type ImageKey = keyof typeof image128Array;
