// Generated by scripts/generate-image-requires.ts — do not edit by hand.
// Run `npm run generate:images` to regenerate this file.

export const images = {
  bg1: require("./1_bg.jpg"),
  bg2: require("./2_bg.jpg"),
  bg3: require("./3_bg.jpg"),
  bg4: require("./4_bg.jpg"),
  bg5: require("./5_bg.jpg"),
  bg6: require("./6_bg.jpg"),
  bg7: require("./7_bg.jpg"),
  bg8: require("./8_bg.jpg"),
  bg9: require("./9_bg.jpg"),
  bg10: require("./focus_bg.jpg"),


} as const;

export const imageArray = [
  images.bg1,
  images.bg2,
  images.bg3,
  images.bg4,
  images.bg5,
  images.bg6,
  images.bg7,
  images.bg8,
  images.bg9,
  images.bg10



] as const;

export type ImageKey = keyof typeof images;
