 
// Generated by scripts/generate-image-requires.ts — do not edit by hand.
// Run `npm run generate:images` to regenerate this file.

export const images = {
  
  cool_cow_red: require("./cool_cow_red.png"),
  david_yellow: require("./david_yellow.png"),
  neon_david: require("./neon_david.png"),
  duck_blue: require("./duck_blue.png"),
  farmer: require("./farmer.png"),
  homeless: require("./homeless.png"),
  long_neck_duck_yellow: require("./long_neck_duck_yellow.png"),
  man: require("./man.png"),
  orange_blue_hat: require("./orange_blue_hat "),
  rainbow_black: require("./rainbow_black.png"),
  retro_fire_dark: require("./retro_fire_dark.png"),
  spidy: require("./spidy.png"),
  yellow: require("./yellow.png"),
  comedy_man: require("./comedy.png"),
  man_reading_window: require("./man_reading_window.png"),
  dvd_neon: require("./dvd_neon.png"),
  optical: require("./optical.png"),
  islamic: require("./785.png"),
} as const;

export const imageArray = [
    images.dvd_neon,
    images.david_yellow,
    images.neon_david,
    images.duck_blue,
    images.farmer,
    images.homeless,
    images.long_neck_duck_yellow,
    images.man,
    images.orange_blue_hat,
    images.rainbow_black,
    images.retro_fire_dark,
    images.spidy,
    images.yellow,
    images.comedy_man,
    images.man_reading_window,
    images.optical,
    images.islamic
    
] as const;

export type ImageKey = keyof typeof images;
