/* eslint-disable */
// Generated by scripts/generate-image-requires.ts — do not edit by hand.
// Run `npm run generate:images` to regenerate this file.

export const images = {
  
  cool_cow_red: require("./cool_cow_red.png"),
  david_yellow: require("./david_yellow.jpg"),
  neon_david: require("./neon_david.jpg"),
  duck_blue: require("./duck_blue.jpg"),
  farmer: require("./farmer.jpg"),
  homeless: require("./homeless.jpg"),
  long_neck_duck_yellow: require("./long_neck_duck_yellow.jpg"),
  luna: require("./luna.png"),
  man: require("./man.png"),
  orange_blue_hat: require("./orange_blue_hat.jpg"),
  rainbow_black: require("./rainbow_black.jpg"),
  retro_fire_dark: require("./retro_fire_dark.jpg"),
  spidy: require("./spidy.avif"),
  spooderman: require("./spooderman.png"),
  yellow: require("./yellow.jpg"),
  comedy_man: require("./comedy.jpg"),
  man_reading_window: require("./man_reading_window.jpg"),
  dvd_neon: require("./dvd_neon.jpg"),
  optical: require("./optical.png"),
} as const;

export const imageArray = [
    images.dvd_neon,
    images.david_yellow,
    images.neon_david,
    images.duck_blue,
    images.farmer,
    images.homeless,
    images.long_neck_duck_yellow,
    images.luna,
    images.man,
    images.orange_blue_hat,
    images.rainbow_black,
    images.retro_fire_dark,
    images.spidy,
    images.yellow,
    images.comedy_man,
    images.man_reading_window,
    images.optical,
    
] as const;

export type ImageKey = keyof typeof images;
